### ISSUE TITLE
reproducing the numbers in the table1 by this repository

### ISSUE THREAD

**Issue by testaccountcvpr** [allenai/interactron#1]
Thanks very much for providing the codes!
I tried to reproduce the numbers in the table1 with this repo:

                                      | AP_50 | AP             | AP_small | AP_medium | AP_large
single_frame_baseline| **0.518** | 0.233        | 0.122      | 0.335.         | 0.404
multi_frame_baseline| 0.525  | 0.224        | 0.077      | 0.326.         | 0.213
Interactron-Rand       | 0.552  | 0.256        | 0.141       | 0.354.         | 0.401
interactron                 | 0.621   | **0.302** | 0.152       | 0.439          | 0.510

The main issue here is the single_frame_baseline, why the  AP_50 of the single_frame_baseline is nearly the same as the multi_frame_baseline?

And why the gap between the AP of interaction(0.302) and the AP of the single_frame_baseline ( 0.233) is not as significant as that of the table1(0.482 - 0.364 = 0.118)?

**Comment by klemenkotar** [comment]
Hi,

Thank you so much for letting me know. I investigated this and found that I must have accidentally uploaded some weights that were fine tuned with some additional data for an extra experiment I did so the comparison here was not fair. I re-uploaded the correct weights now.

Additionally, I find that sometimes installing pytorch with pip will lead to slightly different numbers. Installing pytorch with conda is probably the safest bet. 
I have also fixed the paths to the weights in the config files, so I recommend pulling.

Thanks for your help!
