### ISSUE TITLE
Is it possible to combine this work with one-stage detector such as YOLOv5 or SSD? 

### ISSUE THREAD

**Issue by ShirleyHe2020** [allenai/interactron#2]
Hi Klemen and Roozbeh, I like your work very much and wanna try but I am not sure the proposed structure work with static 2D images .

**Comment by klemenkotar** [comment]
Hi Shirley. Thanks for your interest. Interactron is fundamentally a method for embodied object detection and is thus designed to work in interactive environments where it is possible to move the agent around to obtain multiple views. I am not entirely sure what you mean by working with 2D images. If you would like to chat about possible extensions and future work feel free to email me at klemenk@allenai.org.
